package com.caf.fmradio;

import com.caf.fmradio.IFMRadioServiceCallbacks;

interface IFMRadioService {
    boolean fmOn();
    boolean fmOff();
    boolean fmRadioReset();
    boolean isFmOn();
    boolean isAnalogModeEnabled();
    boolean isFmRecordingOn();
    boolean isSpeakerEnabled();
    boolean fmReconfigure();
    void registerCallbacks(IFMRadioServiceCallbacks cb);
    void unregisterCallbacks();
    boolean mute();
    boolean unMute();
    boolean isMuted();
    boolean startRecording();
    void stopRecording();
    boolean tune(int frequency);
    boolean seek(boolean up);
    void enableSpeaker(boolean speakerOn);
    boolean scan(int pty);
    boolean seekPI(int piCode);
    boolean searchStrongStationList(int numStations);
    boolean cancelSearch();
    String getProgramService();
    String getRadioText();
    int getProgramType();
    int getProgramID();
    boolean setLowPowerMode(boolean bEnable);
    int getPowerMode();
    boolean enableAutoAF(boolean bEnable);
    boolean enableStereo(boolean bEnable);
    boolean isAntennaAvailable();
    boolean isWiredHeadsetAvailable();
    boolean isCallActive();
    int getRssi();
    int getIoC();
    int getMpxDcc();
    int getIntDet();
    int getSINR();
    void setHiLoInj(int inj);
    void delayedStop(long delayMs, int reason);
    void cancelDelayedStop(int reason);
    void requestFocus();
    boolean setSinrSamplesCnt(int samples);
    boolean setSinrTh(int th);
    boolean setIntfDetLowTh(int th);
    boolean setIntfDetHighTh(int th);
    String getExtenRadioText();
    int getExtenCountryCode();
    int getSinrSamplesCnt();
    int getSinrTh();
    int getSearchAlgoType();
    boolean setSearchAlgoType(int algoType);
    int getSinrFirstStage();
    boolean setSinrFirstStage(int stage);
    int getRmssiFirstStage();
    boolean setRmssiFirstStage(int stage);
    int getCFOMeanTh();
    boolean setCFOMeanTh(int th);
    boolean setAfJmpRmssiTh(int th);
    boolean setGoodChRmssiTh(int th);
    boolean setAfJmpRmssiSamplesCnt(int samples);
    int getAfJmpRmssiTh();
    int getGoodChRmssiTh();
    int getAfJmpRmssiSamplesCnt();
    String getSocName();
    boolean setRxRepeatCount(int count);
    long getRecordingStartTime();
    boolean isSleepTimerActive();
    boolean isSSRInProgress();
    boolean isRtPlusSupported();
    boolean isA2DPConnected();
    boolean getIntfDetLowTh();
    boolean getIntfDetHighTh();
    boolean getRxRepeatCount();
    boolean getFmStatsProp();
    void restoreDefaults();
}
