package com.miku.player.profiles

import android.content.Context
import android.util.Log
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.util.UUID

/**
 * Persistence for listening profiles.
 *
 * Two sources, never mixed on disk:
 *  - built-ins: assets/listening_profiles.json, generated by
 *    m500/tools/profiles/gen_listening_profiles.py from AutoEq results and published specs.
 *    Read-only; a new APK can refresh them.
 *  - the user's state: filesDir/listening_profiles_user.json — custom profiles, plus, for
 *    built-ins, only the user's overrides and auto-switch rules, keyed by built-in id. That way an
 *    updated measurement still reaches every field the user did not change.
 *
 * All mutators write the file synchronously (it is a few KB) and republish [profiles].
 */
object ListeningProfileStore {
    private const val TAG = "ListeningProfiles"
    private const val ASSET = "listening_profiles.json"
    private const val USER_FILE = "listening_profiles_user.json"

    /** Port keys for [lastProfileForPort]; same labels MikuOutputVolumes uses. */
    const val PORT_35 = "3.5mm"
    const val PORT_44 = "4.4mm"

    data class Catalog(val generatedAt: String?, val attribution: String?, val profiles: List<ListeningProfile>)

    private data class UserState(
        var currentId: String? = null,
        val portLast: MutableMap<String, String> = mutableMapOf(),
        val custom: MutableList<ListeningProfile> = mutableListOf(),
        val builtinOverrides: MutableMap<String, DspSettings> = mutableMapOf(),
        val builtinAutoSwitch: MutableMap<String, List<AutoSwitchRule>> = mutableMapOf(),
    )

    @Volatile private var catalog: Catalog? = null
    private var user = UserState()
    private var appCtx: Context? = null

    private val _profiles = MutableStateFlow<List<ListeningProfile>>(emptyList())
    val profiles: StateFlow<List<ListeningProfile>> = _profiles

    private val _currentId = MutableStateFlow<String?>(null)
    val currentId: StateFlow<String?> = _currentId

    @Synchronized
    fun load(ctx: Context) {
        if (appCtx != null) return
        appCtx = ctx.applicationContext
        catalog = readCatalog(ctx)
        user = readUser(ctx)
        publish()
    }

    fun catalogInfo(ctx: Context): Catalog? { load(ctx); return catalog }

    fun all(ctx: Context): List<ListeningProfile> { load(ctx); return _profiles.value }

    fun get(ctx: Context, id: String?): ListeningProfile? = id?.let { all(ctx).firstOrNull { p -> p.id == it } }

    fun current(ctx: Context): ListeningProfile? { load(ctx); return get(ctx, _currentId.value) }

    @Synchronized
    fun setCurrent(ctx: Context, id: String?) {
        load(ctx)
        user.currentId = id
        save()
    }

    fun lastProfileForPort(ctx: Context, port: String): String? { load(ctx); return user.portLast[port] }

    @Synchronized
    fun rememberPort(ctx: Context, port: String, id: String) {
        load(ctx)
        if (user.portLast[port] == id) return
        user.portLast[port] = id
        save()
    }

    @Synchronized
    fun setOverrides(ctx: Context, id: String, overrides: DspSettings) {
        load(ctx)
        val custom = user.custom.indexOfFirst { it.id == id }
        if (custom >= 0) {
            user.custom[custom] = user.custom[custom].copy(overrides = overrides)
        } else if (overrides.isEmpty()) {
            user.builtinOverrides.remove(id)
        } else {
            user.builtinOverrides[id] = overrides
        }
        save()
    }

    @Synchronized
    fun setAutoSwitch(ctx: Context, id: String, rules: List<AutoSwitchRule>) {
        load(ctx)
        val custom = user.custom.indexOfFirst { it.id == id }
        if (custom >= 0) {
            user.custom[custom] = user.custom[custom].copy(autoSwitch = rules)
        } else if (rules.isEmpty()) {
            user.builtinAutoSwitch.remove(id)
        } else {
            user.builtinAutoSwitch[id] = rules
        }
        // A device or port belongs to one profile: claiming it here releases it everywhere else.
        val claimed = rules.map { it.kind to it.value.lowercase() }.toSet()
        user.custom.replaceAll { p ->
            if (p.id == id) p else p.copy(autoSwitch = p.autoSwitch.filterNot { (it.kind to it.value.lowercase()) in claimed })
        }
        for (key in user.builtinAutoSwitch.keys.toList()) {
            if (key == id) continue
            val kept = user.builtinAutoSwitch[key].orEmpty().filterNot { (it.kind to it.value.lowercase()) in claimed }
            if (kept.isEmpty()) user.builtinAutoSwitch.remove(key) else user.builtinAutoSwitch[key] = kept
        }
        save()
    }

    /**
     * New custom profile. With [from], it starts as a copy of that profile's EFFECTIVE settings
     * (so a duplicate sounds identical); otherwise it starts from [recommendedFor] its hardware.
     */
    @Synchronized
    fun createCustom(ctx: Context, name: String, hardware: Hardware, from: ListeningProfile? = null): ListeningProfile {
        load(ctx)
        val p = ListeningProfile(
            id = "custom-" + UUID.randomUUID().toString().take(8),
            name = name.trim().ifEmpty { hardware.displayName },
            builtIn = false,
            hardware = hardware,
            recommended = from?.effective ?: ProfileRules.recommendedFor(hardware, null),
            overrides = DspSettings(),
            autoSwitch = emptyList(),
            source = ProfileSource(
                eq = from?.source?.eq?.let { "Copied from ${from.name} ($it)" },
                eqUrl = from?.source?.eqUrl,
                spec = from?.source?.spec,
                rationale = if (from != null) "Copied from ${from.name}" else ProfileRules.rationale(hardware),
            ),
        )
        user.custom.add(p)
        save()
        return p
    }

    @Synchronized
    fun rename(ctx: Context, id: String, name: String) {
        load(ctx)
        val i = user.custom.indexOfFirst { it.id == id }
        if (i < 0 || name.isBlank()) return
        user.custom[i] = user.custom[i].copy(name = name.trim())
        save()
    }

    @Synchronized
    fun delete(ctx: Context, id: String) {
        load(ctx)
        if (!user.custom.removeAll { it.id == id }) return
        if (user.currentId == id) user.currentId = null
        user.portLast.entries.removeAll { it.value == id }
        save()
    }

    // ------------------------------------------------------------------------------ internals

    private fun publish() {
        val builtins = catalog?.profiles.orEmpty().map { b ->
            b.copy(
                overrides = user.builtinOverrides[b.id] ?: DspSettings(),
                autoSwitch = user.builtinAutoSwitch[b.id] ?: b.autoSwitch,
            )
        }
        _profiles.value = user.custom.toList() + builtins
        _currentId.value = user.currentId
    }

    private fun save() {
        val ctx = appCtx ?: return
        val o = JSONObject().apply {
            put("version", 1)
            user.currentId?.let { put("currentId", it) }
            put("portLast", JSONObject().apply { user.portLast.forEach { (k, v) -> put(k, v) } })
            put("custom", JSONArray().apply { user.custom.forEach { put(it.toJson()) } })
            put("builtinOverrides", JSONObject().apply { user.builtinOverrides.forEach { (k, v) -> put(k, v.toJson()) } })
            put("builtinAutoSwitch", JSONObject().apply {
                user.builtinAutoSwitch.forEach { (k, rules) -> put(k, JSONArray().apply { rules.forEach { put(it.toJson()) } }) }
            })
        }
        // Write-then-rename so a crash mid-write cannot leave half a file.
        runCatching {
            val f = File(ctx.filesDir, USER_FILE)
            val tmp = File(ctx.filesDir, "$USER_FILE.tmp")
            tmp.writeText(o.toString(1))
            if (!tmp.renameTo(f)) { f.writeText(o.toString(1)); tmp.delete() }
        }.onFailure { Log.w(TAG, "save failed", it) }
        publish()
    }

    private fun readCatalog(ctx: Context): Catalog = runCatching {
        val o = JSONObject(ctx.assets.open(ASSET).bufferedReader().use { it.readText() })
        Catalog(
            generatedAt = o.optStringOrNull("generatedAt"),
            attribution = o.optStringOrNull("attribution"),
            profiles = o.optJSONArray("profiles").objects().mapNotNull {
                runCatching { ListeningProfile.fromJson(it).copy(builtIn = true) }.getOrNull()
            },
        )
    }.onFailure { Log.w(TAG, "built-in catalog unreadable", it) }.getOrDefault(Catalog(null, null, emptyList()))

    private fun readUser(ctx: Context): UserState = runCatching {
        val f = File(ctx.filesDir, USER_FILE)
        if (!f.exists()) return UserState()
        val o = JSONObject(f.readText())
        UserState(
            currentId = o.optStringOrNull("currentId"),
            portLast = o.optJSONObject("portLast")?.let { pl -> pl.keys().asSequence().associateWith { pl.getString(it) }.toMutableMap() }
                ?: mutableMapOf(),
            custom = o.optJSONArray("custom").objects().mapNotNull {
                runCatching { ListeningProfile.fromJson(it).copy(builtIn = false) }.getOrNull()
            }.toMutableList(),
            builtinOverrides = o.optJSONObject("builtinOverrides")?.let { bo ->
                bo.keys().asSequence().associateWith { DspSettings.fromJson(bo.optJSONObject(it)) }.toMutableMap()
            } ?: mutableMapOf(),
            builtinAutoSwitch = o.optJSONObject("builtinAutoSwitch")?.let { ba ->
                ba.keys().asSequence().associateWith { k ->
                    ba.optJSONArray(k).objects().mapNotNull { AutoSwitchRule.fromJson(it) }
                }.toMutableMap()
            } ?: mutableMapOf(),
        )
    }.onFailure { Log.w(TAG, "user profiles unreadable; starting empty", it) }.getOrDefault(UserState())
}
